#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HBApp.Resource", IsApplication=true)]

namespace HBApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microcharts.Droid.Resource.String.library_name = global::HBApp.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int ganderType = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int healthConditionType = 2131034113;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int asd = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int emptyheart = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int emptyheart_white = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hbimage1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher_background = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int piegauge = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int BSignUp = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int Blogin = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int Bsingnup = 2131165205;
			
			// aapt resource value: 0x7f070020
			public const int HistorychartView = 2131165216;
			
			// aapt resource value: 0x7f070002
			public const int Password = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int Username = 2131165185;
			
			// aapt resource value: 0x7f07001c
			public const int bpm = 2131165212;
			
			// aapt resource value: 0x7f07001a
			public const int btnConsent = 2131165210;
			
			// aapt resource value: 0x7f070022
			public const int btnStop = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int chartView = 2131165219;
			
			// aapt resource value: 0x7f07001b
			public const int chartViewPie = 2131165211;
			
			// aapt resource value: 0x7f070026
			public const int currentHB = 2131165222;
			
			// aapt resource value: 0x7f070021
			public const int dateBtn = 2131165217;
			
			// aapt resource value: 0x7f070008
			public const int dismiss = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int emergency = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int etDob = 2131165201;
			
			// aapt resource value: 0x7f070016
			public const int etDoctorName = 2131165206;
			
			// aapt resource value: 0x7f07000d
			public const int etFirstName = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int etHeight = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int etLastName = 2131165198;
			
			// aapt resource value: 0x7f070027
			public const int etMaxHB = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int etMinHB = 2131165224;
			
			// aapt resource value: 0x7f07000c
			public const int etPassword = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int etUserName = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int etWeight = 2131165200;
			
			// aapt resource value: 0x7f07001d
			public const int fromDatePicker = 2131165213;
			
			// aapt resource value: 0x7f070025
			public const int heartLogo = 2131165221;
			
			// aapt resource value: 0x7f07000a
			public const int ignore = 2131165194;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070017
			public const int imageView2 = 2131165207;
			
			// aapt resource value: 0x7f070024
			public const int modeBtn = 2131165220;
			
			// aapt resource value: 0x7f070007
			public const int myImageViewText = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int piegauge = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int placeholder = 2131165202;
			
			// aapt resource value: 0x7f070014
			public const int spinnerGnder = 2131165204;
			
			// aapt resource value: 0x7f070013
			public const int spinnerHealthCondiotion = 2131165203;
			
			// aapt resource value: 0x7f07001f
			public const int statistics = 2131165215;
			
			// aapt resource value: 0x7f070005
			public const int textView = 2131165189;
			
			// aapt resource value: 0x7f07001e
			public const int toDatePicker = 2131165214;
			
			// aapt resource value: 0x7f070019
			public const int txtStatus = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int txtStep = 2131165208;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_notification = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_signup = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_user_page = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int action_settings = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int action_sign_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int action_sign_in_short = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040013
			public const int background_color = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int clean = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int consent = 2130968590;
			
			// aapt resource value: 0x7f040009
			public const int error_field_required = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int error_incorrect_password = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int error_invalid_email = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int error_invalid_password = 2130968583;
			
			// aapt resource value: 0x7f040011
			public const int history_view = 2130968593;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040012
			public const int live_view = 2130968594;
			
			// aapt resource value: 0x7f04000a
			public const int permission_rationale = 2130968586;
			
			// aapt resource value: 0x7f040002
			public const int prompt_email = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int prompt_password = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int render = 2130968591;
			
			// aapt resource value: 0x7f04000d
			public const int start = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int steps = 2130968588;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyDatePicker = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
